<a href="https://colab.research.google.com/github/aasimusman1212-cyber/basics-of-ml/blob/main/day_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import the data set
import pandas as pd

In [ ]:
#step 2 : load the dataset
insurance = pd.read_csv("/Health_insurance.csv")
print("insurance data set loaded successfully")

insurance data set loaded successfully

In [ ]:
insurance.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
insurance.tail()

      age     sex    bmi  children smoker     region     charges
1333   50    male  30.97         3     no  northwest  10600.5483
1334   18  female  31.92         0     no  northeast   2205.9808
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603

In [ ]:
insurance.shape

(1338, 7)

In [ ]:
insurance.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [ ]:
print("rows :",insurance.shape[0])
print("columns :",insurance.shape[1])
insurance.shape

rows : 1338
columns : 7

(1338, 7)

In [ ]:
print(insurance.columns.tolist())

['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges']

In [ ]:
insurance.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [ ]:
insurance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [ ]:
insurance.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [ ]:
insurance.isnull()

        age    sex    bmi  children  smoker  region  charges
0     False  False  False     False   False   False    False
1     False  False  False     False   False   False    False
2     False  False  False     False   False   False    False
3     False  False  False     False   False   False    False
4     False  False  False     False   False   False    False
...     ...    ...    ...       ...     ...     ...      ...
1333  False  False  False     False   False   False    False
1334  False  False  False     False   False   False    False
1335  False  False  False     False   False   False    False
1336  False  False  False     False   False   False    False
1337  False  False  False     False   False   False    False

[1338 rows x 7 columns]

In [ ]:
insurance.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [ ]:
#how to define the input to the machine
insurance_input_columns = [
    "age",
    "sex",
    "children",
    "smoker",
    "region",
]

insurance_target_column = "charges"

print("input columns :",insurance_input_columns)
print("target column :",insurance_target_column)

input columns : ['age', 'sex', 'children', 'smoker', 'region']
target column : charges

In [ ]:
print("duplicate rows :",insurance.duplicated().sum())

duplicate rows : 1

In [ ]:
#to remove duplicates from the data
insurance = insurance.drop_duplicates().reset_index(drop=True)
print("shape after removing duplicates :",insurance.shape)

shape after removing duplicates : (1337, 7)

In [ ]:
print("duplicate rows :",insurance.duplicated().sum())

duplicate rows : 0

In [ ]:
insurance.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [ ]:
#checking the skewness for the numerical columns
insurance_numerical_columns =[
    "age",
    "bmi",
    "children",
]
insurance[insurance_numerical_columns].skew()

age         0.054781
bmi         0.283914
children    0.937421
dtype: float64

In [ ]:
#filling the missing numerical values
insurance["age"] = insurance["age"].fillna(
    insurance["age"].mean()
    )
insurance["bmi"] = insurance["bmi"].fillna(
    insurance["bmi"].mean()
    )
insurance["children"] = insurance["children"].fillna(
    insurance["children"].median()
    )

In [ ]:
#handling the missing values in the catagorical columns
insurance["sex"] = insurance["sex"].fillna(
    insurance["sex"].mode()[0]
    )
insurance["smoker"] = insurance["smoker"].fillna(
    insurance["smoker"].mode()[0]
    )
insurance["region"] = insurance["region"].fillna(
    insurance["region"].mode()[0]
    )

In [ ]:
#Feature engineering
#label encoding : a preprocessing technique that converts categorical text data into unique numerical integer
#one hot encoding: it is preprocessing technique the allocate the number in the form of yes or no that is 0 or 1 by
#dividing the column respectively according to the data present in it

In [ ]:
#one hot encoding application
insurance_encoded = pd.get_dummies(insurance,
                                   columns=["sex","smoker","region"],dtype=int)
insurance_encoded.head()

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,1,0,0,1,0,0,0,1
1,18,33.770,1,1725.55230,0,1,1,0,0,0,1,0
2,28,33.000,3,4449.46200,0,1,1,0,0,0,1,0
3,33,22.705,0,21984.47061,0,1,1,0,0,1,0,0
4,32,28.880,0,3866.85520,0,1,1,0,0,1,0,0

In [ ]:
x = insurance_encoded.drop(
    "charges",
    axis=1)
y = insurance_encoded["charges"]
print("input shape :",x.shape)
print("input shape :",y.shape)

input shape : (1337, 11)
input shape : (1337,)

In [ ]:
#splittting the data into training and testing

In [ ]:
#testing and splitting the value
from sklearn.model_selection import train_test_split
x_train ,x_test, y_train, y_test = train_test_split (
  x,
  y,
  train_size=0.8,
  test_size=0.2,
random_state=42   #random is a default parameter that should be used commonly for every case
  )
print("training rows :",x_train.shape[0])
print("testing rows :",x_test.shape[0])
print("training rows :",y_train.shape[0])
print("testing rows :",y_test.shape[0])

training rows : 1069
testing rows : 268
training rows : 1069
testing rows : 268